### ISSUE TITLE
Error on first run `Cannot convert undefined or null to object`

### ISSUE THREAD

**Issue by sirlisko** [GreatWizard/coverage-diff-action#12]
I am trying to set up a new job but I am getting the following error:

```
Object.keys(head.total).map((t) => head.total[t].pct),
           ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at run (/home/runner/work/_actions/greatwizard/coverage-diff-action/v1.0.8/dist/index.js:[14](https://github.com/sirLisko/test-coverage/actions/runs/6283765741/job/17064535296#step:7:15)312:12)
```

This is the configuration:

```
      - name: Coverage Diff
        uses: greatwizard/coverage-diff-action@v1.0.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-filename: coverage/coverage-final.json
```

You can see the full job here https://github.com/sirLisko/test-coverage/blob/1d7eba8be0dbe5f47772dbb64d09dfa08d54a22d/.github/workflows/push_ci.yml#L29-L33.
