### ISSUE TITLE
[Possible Bug] Fails to find PR number

### ISSUE THREAD

**Issue by patrick-grow-therapy** [GreatWizard/coverage-diff-action#8]
Hey there! 

I've been attempting to add this action for a bit and figured out that it's failing to grab the PR number (`const issue_number = context?.payload?.pull_request?.number;`). It never enters this [block ](https://github.com/GreatWizard/coverage-diff-action/blob/dfefb6335458e4936d7a688a51ff7d34bf7b97e4/src/index.js#L95)on a fresh pull request and in the else statement (`core.info(diff.results);`), it outputs `undefined`. 

I'm determined to add this action to our workflows but am having trouble getting it to work. I thought maybe the github context wouldn't have the correct path to grab the PR number if I was testing on a draft pull request but ran into the same issue without draft. Do you have any thoughts on why I'm seeing this output? I checked out the PR in the job.

```
      - name: Checkout PR
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
```

Dumping the github context, I don't see the PR number anywhere. I created a new PR to see if its populated on the first commit/opening of the PR but the action still fails. 

Thanks.

Fixed!

Missed `pull_request: {}` for `push` in the workflow header.
